python:
   version: 3
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
        extra_requirements:
          - docs
      - method: setuptools
        path: .
